WINDOW_WIDTH = window.innerWidth;
WINDOW_HEIGHT = window.innerHeight;

VIRTUAL_WIDTH = 432;
VIRTUAL_HEIGHT = 243;

SCALE_FACTOR_WIDTH = WINDOW_WIDTH / VIRTUAL_WIDTH;
SCALE_FACTOR_HEIGHT = WINDOW_HEIGHT / VIRTUAL_HEIGHT;

BACKGROUND_SCROLL_SPEED = 2;
BACKGROUND_LOOP_POINT = 505;

TILE_SPEED = SCALE_FACTOR_HEIGHT;